services:
  db:
    image: postgres:17-alpine
    container_name: go_project_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dynamica_db
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: go_project_app
    ports:
      - "8080:8080"
    environment:
      - DB_DSN=host=db port=5432 user=user password=1234 dbname=dynamica_db sslmode=disable
    depends_on:
      - db

volumes:
  pgdata: